force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>amount</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/debit__c.field-meta.xml
<CustomField>
    <fullName>debit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>debit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TransactionController.cls
public with sharing class TransactionController {
    @AuraEnabled(cacheable=true)
    public static List<Transaction__c> getTransactions(Id userId) {
        
        return [SELECT Id, amount__c, debit__c FROM Transaction__c WHERE OwnerId = :userId LIMIT 50];
    }

    @AuraEnabled
    public static void deleteTransactions(list<Id> transList){
        try {
            list<Transaction__c> listTransToDelete = new list<Transaction__c>();
            System.debug('lsttransIds ====> ' + transList);
            for(Id idTrans : transList) {
                listTransToDelete.add(new Transaction__c(Id = idTrans));
            }
            if(!listTransToDelete.isEmpty()) {
                delete listTransToDelete;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}
 